/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "commons"

include("commons-units")
include("commons-utils")
include("commons-collect")


// Check that every subproject has a custom build file, based on the project name.
//   Got this idiom from org.junit.jupiter's gradle setup. Avoid having numerous "commons-collect.gradle.kts" files.
rootProject.children.forEach { project ->
    project.buildFileName = "${project.name}.gradle.kts"
    require(project.buildFile.isFile) {
        "${project.buildFile} must exist"
    }
}